package renderers

import (
	"fmt"
	"strings"
	"time"

	"github.com/release-foundry/internal/domain"
)

var typeOrder = []string{"feature", "fix", "performance", "security", "infrastructure", "other"}

var typeHeaders = map[string]string{
	"feature":        "### ✨ Features",
	"fix":            "### 🐛 Bug Fixes",
	"performance":    "### ⚡ Performance",
	"security":       "### 🔒 Security",
	"infrastructure": "### 🏗️ Infrastructure",
	"other":          "### 🔄 Other",
}

// GithubRelease renders a WeeklySummary into a GitHub release body (Markdown).
// Groups PRs by type with emoji headers, deterministic order, no LLM.
func GithubRelease(summary domain.WeeklySummary) string {
	byType := make(map[string][]domain.PullRequest)
	for _, pr := range summary.PullRequests {
		t := pr.Type
		if _, known := typeHeaders[t]; !known {
			t = "other"
		}
		byType[t] = append(byType[t], pr)
	}

	var b strings.Builder
	b.WriteString("## What's Changed\n")

	wrote := false
	for _, t := range typeOrder {
		prs := byType[t]
		if len(prs) == 0 {
			continue
		}
		b.WriteByte('\n')
		b.WriteString(typeHeaders[t])
		b.WriteByte('\n')
		for _, pr := range prs {
			fmt.Fprintf(&b, "- %s (#%d, @%s)\n", cleanTitle(pr.Title), pr.Number, pr.Author)
		}
		wrote = true
	}

	if !wrote {
		b.WriteString("\nNo user-facing changes in this release.\n")
	}

	b.WriteByte('\n')
	fmt.Fprintf(&b, "_Generated by release-foundry on %s_\n",
		time.Now().UTC().Format("2006-01-02"))

	return b.String()
}

// GithubReleaseBatch renders a BatchSummary into one combined GitHub release body.
func GithubReleaseBatch(batch domain.BatchSummary) string {
	var b strings.Builder
	for i, repo := range batch.Repositories {
		if i > 0 {
			b.WriteString("\n---\n\n")
		}
		fmt.Fprintf(&b, "## %s\n\n", repo.Repository)
		inner := GithubRelease(repo)
		// Strip the leading "## What's Changed\n" when embedding in a batch
		inner = strings.TrimPrefix(inner, "## What's Changed\n")
		b.WriteString(inner)
	}
	return b.String()
}

// cleanTitle strips the conventional commit prefix from a PR title for display.
// "feat: add X" → "add X", "fix(scope): Y" → "Y"
func cleanTitle(title string) string {
	if idx := strings.Index(title, ": "); idx > 0 {
		return strings.TrimSpace(title[idx+2:])
	}
	return title
}
