name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  goreleaser:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    uses: ./.github/workflows/go-binary-release.yml
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      NOTARIZATION_ISSUER_ID: ${{ secrets.NOTARIZATION_ISSUER_ID }}
      NOTARIZATION_KEY_ID: ${{ secrets.NOTARIZATION_KEY_ID }}
      NOTARIZATION_KEY: ${{ secrets.NOTARIZATION_KEY }}
